@base_url = https://localhost:7015/usuario

### Listar Usuarios ###
GET {{base_url}}/listar

### Criar Usuario ###
POST {{base_url}}/cadastrar
Content-Type: application:json
{
    "Nome": "nome",
    "Nascimento": "data"
}